# Generated by Django 4.1 on 2024-06-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_create_at_users_update_at_posts_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='No comment', max_length=500),
            preserve_default=False,
        ),
    ]
